Repository replikativ/datahike, pull requests merged in 2020-09, with the labels that each got.

#224 Apply CircleCI Orb to normalize CI
  .circleci/config.yml
  bin/run-integrationtests
  bin/run-unittests
Labels: Ready for review

#220 fix history upsert tx
  src/datahike/db.cljc
  test/datahike/test/purge.cljc
  test/datahike/test/time_variance.cljc
Labels: Ready for review

#225 Define formatting guidelines
  .circleci/config.yml
  dev/sandbox.clj
  project.clj
  src/datahike/api.cljc
  src/datahike/connector.cljc
  src/datahike/core.cljc
  src/datahike/datom.cljc
  src/datahike/db.cljc
  src/datahike/impl/entity.cljc
  src/datahike/index.cljc
  src/datahike/index/hitchhiker_tree.cljc
  src/datahike/js.cljs
  src/datahike/lru.cljc
  src/datahike/migrate.clj
  src/datahike/query.cljc
  src/datahike/query_v3.cljc
  src/datahike/schema.cljc
  src/deps.cljs
  test/datahike/integration_test/config_record_file_test.clj
  test/datahike/test.cljc
  test/datahike/test/cljs.cljc
  test/datahike/test/components.cljc
  test/datahike/test/conn.cljc
  test/datahike/test/core.cljc
  test/datahike/test/db.cljc
  test/datahike/test/entity.cljc
  test/datahike/test/explode.cljc
  test/datahike/test/filter.cljc
  test/datahike/test/ident.cljc
  test/datahike/test/index.cljc
  test/datahike/test/listen.cljc
  test/datahike/test/lookup_refs.cljc
  test/datahike/test/lru.cljc
  test/datahike/test/migrate.clj
  test/datahike/test/pull_api.cljc
  test/datahike/test/purge.cljc
  test/datahike/test/query.cljc
  test/datahike/test/query_aggregates.cljc
  test/datahike/test/query_find_specs.cljc
  test/datahike/test/query_fns.cljc
  test/datahike/test/query_interop.cljc
  test/datahike/test/query_not.cljc
  test/datahike/test/query_or.cljc
  test/datahike/test/query_pull.cljc
  test/datahike/test/query_rules.cljc
  test/datahike/test/query_v3.cljc
  test/datahike/test/schema.cljc
  test/datahike/test/store.cljc
  test/datahike/test/time_variance.cljc
  test/datahike/test/transact.cljc
  test/datahike/test/upsert.cljc
  test/datahike/test/validation.cljc
Labels: Ready for review

#228 Update documentation
  doc/backend-development.md
  doc/config.md
Labels: Ready for review

#203 202 fix historical db printer
  src/datahike/db.cljc
  test/datahike/test/time_variance.cljc
Labels: Ready for review, bug

#229 197 entity spec
  .gitignore
  README.md
  doc/entity_spec.md
  src/datahike/db.cljc
  src/datahike/schema.cljc
  test/datahike/test/db.cljc
  test/datahike/test/entity_spec.cljc
  test/datahike/test/schema.cljc
Labels: Ready for review

#192 hashes are not correct when reconnecting
  src/datahike/connector.cljc
  src/datahike/db.cljc
  test/datahike/test/api.cljc
  test/datahike/test/conn.cljc
Labels: Ready for review

#234 ADR build tooling
  doc/adl/adr-001-build-tooling.org
Labels: documentation
